"""Validate and report the maintained STG matrix without source discovery."""
import argparse
import sys
from pathlib import Path

if __package__ in (None, ''):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.common.database import canonical_json
from tools.common.stg_matrix import load_matrix, matrix_counts, TYPES


def markdown_report(counts):
    lines = ['# Arcade STG master matrix reconciliation', '',
             'The approved three-part matrix replaces the earlier incomplete matrix. '
             'This report reconciles the supplied dataset only; it does not claim public MiSTer availability.', '',
             '| Measure | Count |', '|---|---:|']
    for key in ('total_rows', 'distinct_designs', 'tate_rows', 'distinct_tate_designs', 'yoko_rows',
                'hardware_resolved_rows', 'hardware_unresolved_rows', 'canonical_parent_rows'):
        lines.append('| ' + key.replace('_', ' ').capitalize() + ' | ' + str(counts[key]) + ' |')
    lines += ['', 'Hardware values are supplied classifications, including broad family labels. '
              'A populated value is not an independently researched platform assertion.', '',
              '## TATE types', '', '| Type | Description | Rows |', '|---|---|---:|']
    for key, value in counts['tate_types'].items():
        lines.append(f'| {key} | {TYPES[key]} | {value} |')
    for heading, field in [('Developer', 'by_developer'), ('Hardware/System', 'by_hardware')]:
        lines += ['', '## ' + heading, '',
                  '| ' + heading + ' | Rows | TATE rows | YOKO rows | Distinct TATE designs |',
                  '|---|---:|---:|---:|---:|']
        for name, values in counts[field].items():
            lines.append('| ' + name + ' | ' + ' | '.join(str(values[k]) for k in
                         ('rows', 'tate_rows', 'yoko_rows', 'distinct_tate_designs')) + ' |')
    lines += ['', '## Canonical design and hardware rows', '',
              'DoDonPachi DaiOuJou Tamashii remains an IGS PGM2 hardware/release row with '
              'DoDonPachi DaiOuJou as its canonical parent. The two rows count as one design.', '',
              'The four IGS PGM rows remain separate designs. Bee Storm retains its supplied '
              'attribution uncertainty and the explicitly requested year 2001. Other years remain null.', '',
              'Magical Spot II remains the supplied alternate/variant of Magical Spot.', '',
              '## Scope', '', 'No upstream inventories were refreshed for this reconciliation. '
              'No collection artifact or availability claim is generated by this report.', '']
    return '\n'.join(lines).encode('utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', type=Path)
    args = parser.parse_args()
    counts = matrix_counts(load_matrix())
    if args.report:
        args.report.write_bytes(markdown_report(counts))
    print(canonical_json(counts).decode(), end='')


if __name__ == '__main__':
    main()
